### ISSUE TITLE
Application freeze and not show handler

### ISSUE THREAD

**Issue by Caceresenzo** [RohitSurwase/UCE-Handler#2] opened 2018-04-28 22:31 UTC
Hi

I have imported your libs in my apps, and do everything like the exemple, try crashing it, and the application was just frozen...

So i try with your exemple direcly, i created a new project and imported your exemple, compiled it, and was not working either...

What should i do ?
With logcat i can see that you handler has been installed and the exception has been caught, but the is just waiting, completly frozen

- Enzo

**Comment by RohitSurwase** [comment] 2018-04-29 08:52
Please make sure you have added dependencies to the project level build.gradle and the app level build.gradle. After that, you need to initialize UCE-Handler in your Application class's onCreate().

If you have already done this try disabling ( .setUCEHEnabled(false) ) the library and see if your app works (it should show default crash dialog).
Additionally, can you share the logs?

**Comment by Caceresenzo** [comment] 2018-04-29 11:08
I don't use Android Studio with Gradle, I use Eclipse Android Developement Tool

That work the shame but ADT don't support gradle, so you have to import all project yourself and say you want to add them to your project, and that work perfeclty fine

-
By disabling your library with .setUCEHEnabled(false), the default crash "Stopped working" message show again;

But if i remove this line, the app just froze and stay like this (it become black most of the time)

Here is logcat output of my application: (Put in pastebin, because that was not practical)
https://pastebin.com/8g5gSBLR

As you can see, your handler has been called but nothing append

And here is my Application class (defined in the AndroidManifest.xml)
![image](https://user-images.githubusercontent.com/7386242/39405898-5e82a5cc-4bae-11e8-889b-59bf8c50b7d0.png)

**Comment by RohitSurwase** [comment] 2018-04-29 11:16
So if you are using ADT, make sure after you download the project, import only "uce_handler" out of it. That's what you will need. I'll look into the logs and get back to you.

**Comment by Caceresenzo** [comment] 2018-04-29 11:34
I am already importing only the uce_handler. I even check if the libs was depending of any libs

- Enzo

**Comment by RohitSurwase** [comment] 2018-04-29 12:18
Are you using any other custom exception handler? or similar library for the same?
Please make sure if you are not doing something in wrong way. As apart from your app, the included example app should definitely work if used as it is.
I have even tried causing an exception (as you have) in the library but still, it is not freezing as you are experiencing.

**Comment by Caceresenzo** [comment] 2018-04-29 12:24
I am not using any other libraries

I try with your example app, because i was not understanding why that was not working
So i imported it into eclipse, add appcompat and your libraries, but the example app freeze too..

If you want i can export you your example app and you will see by yourself

I think i forgot to mention that the only difference with our 2 example compiled app, was the fact that my app used the AppTheme (i was forced to put minSdk to 21 and targetSdk to 27, otherwise eclipse wasn't compiling because he found that if no sdk information was provided, the default was 0 or 1, and throw an exception saying that this version don't support Runtime Permission)

 - Enzo

**Comment by RohitSurwase** [comment] 2018-04-29 12:37
If you don't mind, please share the example app.
The minSdkVersion of the library is 14.

**Comment by Caceresenzo** [comment] 2018-04-29 12:43
http://caceresenzo.esy.es/repo/enzo/code/test/Android.App.HandlerTest.apkx

(sorry but this host don't allow .apk file or .exe file on their site, i just rename the file extension)
(and btw, this application is not signed)

**Comment by RohitSurwase** [comment] 2018-04-29 12:47
Thanks but I was asking about the source of the example app which you have modified and not working. Share the compressed file with me.

**Comment by Caceresenzo** [comment] 2018-04-29 12:50
http://caceresenzo.esy.es/repo/enzo/code/test/Android.App.HandlerTest.7z

(the project name was Android.App.ExpandableLayoutTest or something like that, because i use this example project and remove everything and use this project for your example app (i was lazy creating a new project))

**Comment by RohitSurwase** [comment] 2018-04-29 13:22
The source of the example app you have shared does not have the library as a module included. Please review your project setup once again. I have tested it several times with different scenarios nothing happing like yours. Another thing, a suggestion, try upgrading to Android Studio.

I am closing this issue as it is either because of wrong setup or deprecated Eclipse and APT.

**Comment by Caceresenzo** [comment] 2018-04-29 13:23
Check out the project.properties file, all libraries are here!

**Closed as completed** 2018-04-29 13:23 UTC

**Comment by RohitSurwase** [comment] 2018-04-29 13:34
Yes, correct me if I'm wrong, you have imported the project but not the library, the library is in submodule
`compile 'com.github.RohitSurwase.UCE-Handler:uce_handler:1.3'`
I have not used eclipse for ages so cannot be sure.

**Comment by Caceresenzo** [comment] 2018-04-29 13:38
With eclipse, a library is a project that you need to configure "As Library", eclipse will do all the work if you tell him (with project.properties (with a GUI)) to use this libraries, the compilation will exactly do the same as android studio for the "compile 'com.github.RohitSurwase.UCE-Handler:uce_handler:1.3'" thing

Eclipse work fine with lib, just as an example, my main project depend of 12 another libraries (interpreted as independant project by eclipse)

**Comment by RohitSurwase** [comment] 2018-04-29 13:44
Okay, let me try it another way, share your main app's crash log without adding the library or disabling the library.
By the way, I still doubt why the default example is not working in your case.

**Comment by Caceresenzo** [comment] 2018-04-29 13:52
I removed your library of my project, and re-add the "crash" back

my code is just when my second activity start, it throw an exception
`
@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_video);
		<... code ...>
		 throw new RuntimeException();
	}
`

so here the crahs report:
https://pastebin.com/waMrfTC4

EDIT: code seems to not format, sorry

**Comment by RohitSurwase** [comment] 2018-04-29 14:17
It looks like your main app is causing out of memory exception because of the library. Maybe your device is not able to hold the stack trace in the memory. Try increasing the heap size temporary like `largeHeap="true"` And tell me the result.

**Comment by Caceresenzo** [comment] 2018-04-29 14:21
I got 2 devices, one is running android 8 (2gb ram) and the other one 5.1 (1gb ram), i have tested on both phone, and the same result occure, the app just froze...

I just added the `largeHeap="true"` to the android manifest but the result stay like before

- Enzo

**Comment by RohitSurwase** [comment] 2018-04-29 14:35
In that case no luck for both of us. I can not reproduce it on my side, different IDE environment. You are doing your best. The library is tested multiple times and also being used by many without any issues. Thanks for reporting the issue though.

**Comment by Caceresenzo** [comment] 2018-04-29 14:45
Even if the problem persist, thanks you for your time helping me!

I will try to do thing tomorow, i will come to post solution, if any, as soon as possible

**Comment by Caceresenzo** [comment] 2018-04-29 16:20
FOUND!!!!!!!!!!!!!!!!

Eclipse ADT is pretty old and not maintained, SO HERE THS FUC*ING SOLUTION:

I edit a lot your code, searching what could cause this error;
After 1 hour, i found that `application.startActivitity(intent);` was blocking!

Soooooooooooooooooooooooo,
Why this operation was blocking ? I tried to do the instruction in a thread and found that was because the instruction was crashing the thread again.
And the reason was simple, because Your Library Activity was NOT registered! Eclipse ADT is capable to mix R.java file, but is NOT capable (yet i think) to mix AndroidManifest.xml...

![image](https://user-images.githubusercontent.com/7386242/39408651-cdc058f0-4bd9-11e8-9c4a-2775a9764a18.png)

And it finally work! Thanks you!

But can you edit your Readme.rm to say that if the developer is using Eclipse ADT, he need to register, BY HAND, your crash report activity!

Thanks for you libs, he will be helpful!

**Comment by RohitSurwase** [comment] 2018-04-29 16:27
Yes! Of course, I will add this suggestion to README file.
Thanks for replying your solution.
I hope soon you will start using Android Studio as your default IDE.
